spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: testData
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  datasource:
    url: jdbc:mysql://localhost:3306/zqf
    username: root
    password: 123987
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect