spring:
  datasource:
    password: 123987
    username: root
    url: jdbc:mysql://localhost:3306/mytest
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        dialect: org.hibernate.dialect.MySQL5Dialect